server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://armoury-db.cduurjrydbyh.ap-northeast-2.rds.amazonaws.com/Test?autoReconnect=true
    username: root
    password: cap5arm00
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전